name: Deploy Website
on:
  push:
    branches:
      - main

# GitHub Actions 권한 부여를 위한 설정
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Node.js 24 경고 대응을 위한 환경 변수
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Site
        run: hugo --gc --minify

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Git 식별자 명시
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'